### ISSUE TITLE
Videos app does not open

### ISSUE THREAD

**Issue by autumnwalker** [owncloud/videos#14]
When clicking on the videos app in OC 8.0.2-8 it just redirects to the files app.

No errors shown in the OC log.

**Comment by autumnwalker** [comment]
Thanks DeepDiver1975.

Unfortunately I'm now just getting a blank, white page; however, the URL is correct and it no longer redirects to /files.

### Log File Output
```
{"reqId":"59e88aebabdacf680a7cf16057e51f50","remoteAddr":"<removed>","app":"index","message":"Exception: {\"Message\":\"js file not found: script:3rdparty\\\/l10n\\\/en serverroot:\\\/var\\\/www\\\/owncloud\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(156): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(107): OC_TemplateLayout::findJavascriptFiles(Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template.php(118): OC_TemplateLayout->__construct('user', 'videos')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(103): OC_Template->fetchPage()\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/videos\\\/index.php(41): OC\\\\Template\\\\Base->printPage()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 [internal function]: __lambda_func(Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('?lambda_1661', Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(767): OC\\\\Route\\\\Router->match('\\\/apps\\\/videos')\\n#9 \\\/var\\\/www\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template\\\/resourcelocator.php\",\"Line\":46}","level":4,"time":"2015-04-09T15:17:51+00:00"}
{"reqId":"59e88aebabdacf680a7cf16057e51f50","remoteAddr":"<removed>","app":"PHP","message":"js file not found: script:3rdparty\/l10n\/en serverroot:\/var\/www\/owncloud at \/var\/www\/owncloud\/lib\/private\/template\/resourcelocator.php#46","level":3,"time":"2015-04-09T15:17:51+00:00"}
```

**Comment by DeepDiver1975** [comment]
Yes this app is totally broken. It reuses assets of files-videoplayer which is a total no go design wise.

No idea in which state the video player is.

Most probably both apps are not really for oc8+

**Comment by autumnwalker** [comment]
Oh, does this app require files_videoplayer to be present in /apps?
